# Generated by Django 5.1.4 on 2026-03-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único del cliente, ej: ENT01', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_name', models.CharField(default='Mi Cliente', max_length=200)),
                ('client_subtitle', models.CharField(default='Zona de entretenimiento', max_length=300)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('client_favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('branding_primary_color', models.CharField(default='#1400FF', max_length=9)),
                ('branding_primary_hover', models.CharField(default='#0f00cc', max_length=9)),
                ('branding_primary_dark', models.CharField(default='#0a0099', max_length=9)),
                ('branding_primary_light', models.CharField(default='#6b5cff', max_length=9)),
                ('branding_accent_color', models.CharField(default='#FF6600', max_length=9)),
                ('branding_accent_light', models.CharField(default='#ff8533', max_length=9)),
                ('branding_background_color', models.CharField(default='#f0f4f8', max_length=9)),
                ('branding_card_background', models.CharField(default='#ffffff', max_length=9)),
                ('branding_text_primary', models.CharField(default='#1e293b', max_length=9)),
                ('branding_text_muted', models.CharField(default='#636e72', max_length=9)),
                ('branding_border_color', models.CharField(default='#e2e8f0', max_length=9)),
                ('kiosk_exit_password', models.CharField(default='1234', max_length=50)),
                ('kiosk_inactivity_timeout_seconds', models.PositiveIntegerField(default=120)),
                ('kiosk_show_best_scores', models.BooleanField(default=True)),
                ('game_memory_enabled', models.BooleanField(default=True)),
                ('game_memory_pairs', models.PositiveIntegerField(default=8)),
                ('game_puzzle_enabled', models.BooleanField(default=True)),
                ('game_reaction_enabled', models.BooleanField(default=True)),
                ('game_simon_enabled', models.BooleanField(default=True)),
                ('game_simon_colors', models.PositiveIntegerField(default=9)),
                ('game_simon_speed_ms', models.PositiveIntegerField(default=400)),
                ('game_whack_enabled', models.BooleanField(default=True)),
                ('game_whack_duration_seconds', models.PositiveIntegerField(default=30)),
                ('game_speedtap_enabled', models.BooleanField(default=True)),
                ('game_speedtap_duration_seconds', models.PositiveIntegerField(default=30)),
                ('game_balloonpop_enabled', models.BooleanField(default=True)),
                ('game_balloonpop_duration_seconds', models.PositiveIntegerField(default=45)),
                ('records_enabled', models.BooleanField(default=True)),
                ('records_require_rut', models.BooleanField(default=True)),
                ('records_require_name', models.BooleanField(default=True)),
                ('records_max_entries_per_game', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Cliente',
                'verbose_name_plural': 'Configuraciones de Clientes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(choices=[('memory', 'Memory Match'), ('puzzle', 'Slide Puzzle'), ('reaction', 'Reaction Time'), ('simon', 'Simon Says'), ('whack', 'Atrapa el Logo'), ('speedtap', 'Speed Tap'), ('balloonpop', 'Balloon Pop')], max_length=50)),
                ('player_name', models.CharField(max_length=200)),
                ('player_rut', models.CharField(blank=True, default='', max_length=20)),
                ('score', models.IntegerField()),
                ('is_higher_better', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='kiosk.clientconfig')),
            ],
            options={
                'verbose_name': 'Entrada de Leaderboard',
                'verbose_name_plural': 'Entradas de Leaderboard',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'game_id', '-created_at'], name='kiosk_leade_client__41185f_idx')],
            },
        ),
    ]
